name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Install dependencies
      run: pnpm install

    - name: Run Linter
      run: pnpm run lint

    - name: Run Unit Tests
      run: pnpm run test:ci

    - name: Build Next.js App
      run: pnpm run build
